### ISSUE TITLE
Can't get the conjugate.

### ISSUE THREAD

**Issue by Niriel** [martinling/numpy_quaternion#1]
``` python
>>> import numpy as np
>>> import quaternion
>>> q = np.quaternion(1, 2, 3, 4)
>>> print q, q.conjugate()
quaternion(1, 2, 3, 4) quaternion(1, 2, 3, 4)
```

I would have expected the second one to be quaternion(1, -2, -3, -4).

**Comment by martinling** [comment]
You can get the conjugate with conjugate(q).

The reason that q.conjugate() doesn't work is that this method is provided at a lower level by NumPy to all scalar and array objects, and doesn't honor the fact that the quaternion class registers its own conjugate ufunc.

This is one of several limitations of this package related to the design of NumPy's dtype extensibility. This particular problem could be solved by having the quaternion class override the conjugate method, but the same problem would still arise for arrays of quaternions, where it cannot be fixed without patching the ndarray class.

For more background on these issues see: http://www.mail-archive.com/numpy-discussion@scipy.org/msg32884.html

**Comment by Niriel** [comment]
Ohhh, subtle!  Thanks for that :).
