### ISSUE TITLE
quaternion_isnonzero() doesn't appear to work properly

### ISSUE THREAD

**Issue by jhallyburton** [martinling/numpy_quaternion#10]
From code inspection (I can't get nq to work under Windows) it looks like the &&s in quaternion_isnonzero() should be ||s. I.e., if any component is nonzero, the entire quaternion is nonzero. Right now, you need all components to be nonzero...that doesn't look right to me.

**Comment by moble** [comment]
This problem is fixed in a newer version of this package, found [here](https://github.com/moble/quaternion).
