### ISSUE TITLE
eulerzyx and eulerxyz and angle axis constructors

### ISSUE THREAD

**Issue by legalup** [martinling/numpy_quaternion#11]
hello, 

i really like the elegance and simplicity of what you have done.

in my application, i will need to convert (back and forth) to rotation matrices. i will also need to construct a quaternion form angle,axis.

would it be OK for me to add these features?

**Comment by moble** [comment]
These features have been added to a newer version of this package, found [here](https://github.com/moble/quaternion).  Note that axis-angle is such a simple application of `quaternion.exp` that I prefer not to have a separate function for it.
