### ISSUE TITLE
Issue with ufunc loop registration?

### ISSUE THREAD

**Issue by vladu** [martinling/numpy_quaternion#2]
Hello,

I attempted to follow along with the README, and the package built and installed nicely. However, when running the example code, I run into the following issue:

``` python
 >>> import numpy as np
 >>> import quaternion
 >>> np.quaternion(1,0,0,0)
 quaternion(1, 0, 0, 0)
 >>> q1 = np.quaternion(1,2,3,4)
 >>> q2 = np.quaternion(5,6,7,8)
 >>> q1 * q2
TypeError                                 Traceback (most recent call last)
[... ...]
TypeError: ufunc 'multiply' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'
```

Any ideas what might be causing this? I'm using numpy version 1.6.0, if that matters.

**Comment by vladu** [comment]
Never mind, I see it's a bug in numpy. Looks like it was fixed in a pull request, but hasn't been incorporated into trunk or released yet.

https://github.com/numpy/numpy/pull/175

**Comment by martinling** [comment]
For anyone else reading: this means that numpy_quaternion is unusable on numpy 1.6.0 or 1.6.1, but should work okay with the next numpy version when it is released. If you're desperate to use numpy_quaternion before then, downgrade to numpy 1.5.1 or get a bleeding edge build of numpy.
