### ISSUE TITLE
ufuncs not working properly

### ISSUE THREAD

**Issue by alexbw** [martinling/numpy_quaternion#3]
Working with Python 2.7, NumPy 1.6.2, Mac OS 10.8.2

In [1]: import quaternion

In [2]: q = np.quaternion(1,0,0,0)
## In [3]: q*q

TypeError                                 Traceback (most recent call last)
<ipython-input-3-8e55285dbb0b> in <module>()
----> 1 q*q

TypeError: ufunc 'multiply' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'
## In [4]: q+q

TypeError                                 Traceback (most recent call last)
<ipython-input-5-1579469501f5> in <module>()
----> 1 q+q

TypeError: ufunc 'add' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'

**Comment by mvernacc** [comment]
i'm having the same issue

**Comment by moble** [comment]
This problem is fixed in a newer version of this package, found [here](https://github.com/moble/quaternion).

**Comment by martinling** [comment]
Hi Mike,

I had no idea that you were doing cool new stuff with this old bit of code! What a pleasant surprise. I will update my repository to include a pointer to yours.
