### ISSUE TITLE
Is this where I can ask for help?

### ISSUE THREAD

**Issue by OlyDLG** [martinling/numpy_quaternion#7]
Hi!  Just cloned, trying to install under Python 2.7.3, in Windows 7 HP SP1.  python setup.py build returns: 

running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler opti
ons
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler opt
ions
running build_src
build_src
building extension "quaternion.numpy_quaternion" sources
quaternion - nothing done with h_files = ['quaternion.h']
build_src: building npy-pkg config files
running build_py
running build_ext
No module named msvccompiler in numpy.distutils; trying from distutils
customize MSVCCompiler
customize MSVCCompiler using build_ext
building 'quaternion.numpy_quaternion' extension
compiling C sources
error: Unable to find vcvarsall.bat

I found a vcvarsall.bat in C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\ and added that to my path:

C:\Users\DLG\Documents\Git\numpy_quaternion>path
PATH=...;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\;

Still no love.  Help!

OlyDLG

**Comment by moble** [comment]
I don't know anything about MSVC, but some problems with compilation have been fixed in a newer version of this package, found [here](https://github.com/moble/quaternion).

**Comment by martinling** [comment]
Although this hasn't been confirmed as fixed in moble's version, I'm going to close this issue. If anyone still finds problems with MSVC, please raise an issue there.
