### ISSUE TITLE
Scalar double/float conversion fail

### ISSUE THREAD

**Issue by mcflan** [martinling/numpy_quaternion#8]
Thanks for making this quaternion library available to the community. I was mucking around with it when I discovered a possible bug:

Try this in ipython:

```
In [1]: import numpy as np

In [2]: import quaternion

In [3]: q = np.quaternion(1, 0, 0, 0)

In [4]: 2 * q
Out[4]: quaternion(2, 0, 0, 0)

In [5]: 2.0 * q
Out[5]: quaternion(4.61169e+18, 0, 0, 0)
```

Oops!

I think this is due to line 339 in numpy_quaternion.c:

```
  MAKE_T_TO_QUATERNION(DOUBLE, npy_uint64);
```

In the macro above at line 325, this results in a cast from a 64 bit int to a double,
which is probably not what you want. I've never written a python module like this
before, but don't quite understand why line 339 isn't:

```
MAKE_T_TO_QUATERNION(DOUBLE, npy_double);
```

Which seems to fix the problem.
Line 338 might cause a similar problem with floats but I can't reproduce this.

(If, for some reason I don't understand, it is actually necessary to transfer doubles from numpy as 64-bit ints, then you probably need to use some kind of type punning instead of a type cast at line 331.)

I submit the following patch:

```
--- numpy_quaternion_original.c 2014-03-31 23:45:11.421316858 +0100
+++ numpy_quaternion.c  2014-03-31 23:50:26.406878766 +0100
@@ -335,8 +335,8 @@
     }                                                                          \
 }

-MAKE_T_TO_QUATERNION(FLOAT, npy_uint32);
-MAKE_T_TO_QUATERNION(DOUBLE, npy_uint64);
+MAKE_T_TO_QUATERNION(FLOAT, npy_float);
+MAKE_T_TO_QUATERNION(DOUBLE, npy_double);
 MAKE_T_TO_QUATERNION(LONGDOUBLE, npy_longdouble);
 MAKE_T_TO_QUATERNION(BOOL, npy_bool);
 MAKE_T_TO_QUATERNION(BYTE, npy_byte);
```

This fixes the problem for me, but could well introduce other ones I haven't discovered yet. I am very new to numpy so I fully admit that this all might be due to a problem with my own python/numpy installation, in which case I apologise.

Best regards,

James.

**Comment by moble** [comment]
This problem is fixed in a newer version of this package, found [here](https://github.com/moble/quaternion).
